<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Attendance Report - {{ $subject->code }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1e293b; }
        .header { background: #0f2864; color: white; padding: 20px 24px; margin-bottom: 20px; }
        .header h1 { font-size: 20px; font-weight: bold; }
        .header p { font-size: 11px; opacity: 0.8; margin-top: 4px; }
        .info-row { display: flex; gap: 20px; padding: 0 24px; margin-bottom: 16px; }
        .info-box { background: #f1f5f9; border-radius: 8px; padding: 10px 16px; flex: 1; }
        .info-box .label { font-size: 10px; color: #64748b; text-transform: uppercase; }
        .info-box .value { font-size: 14px; font-weight: bold; color: #1e293b; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin: 0 24px; width: calc(100% - 48px); }
        th { background: #1e40af; color: white; padding: 10px 12px; text-align: left; font-size: 11px; }
        td { padding: 9px 12px; border-bottom: 1px solid #e2e8f0; font-size: 11px; }
        tr:nth-child(even) td { background: #f8fafc; }
        .flagged td { background: #fff1f2 !important; }
        .badge { padding: 3px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .badge-ok { background: #dcfce7; color: #16a34a; }
        .badge-low { background: #fee2e2; color: #dc2626; }
        .footer { margin-top: 20px; padding: 10px 24px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student Attendance Report</h1>
        <p>SLIATE Dambawela · Department of Information Technology · HNDIT Programme</p>
    </div>

    <div class="info-row">
        <div class="info-box">
            <div class="label">Subject</div>
            <div class="value">{{ $subject->name }}</div>
        </div>
        <div class="info-box">
            <div class="label">Code</div>
            <div class="value">{{ $subject->code }}</div>
        </div>
        <div class="info-box">
            <div class="label">Batch</div>
            <div class="value">{{ $subject->batch->name }}</div>
        </div>
        <div class="info-box">
            <div class="label">Lecturer</div>
            <div class="value">{{ $subject->lecturer->name ?? 'N/A' }}</div>
        </div>
        <div class="info-box">
            <div class="label">Total Sessions</div>
            <div class="value">{{ $sessions->count() }}</div>
        </div>
        <div class="info-box">
            <div class="label">Generated On</div>
            <div class="value">{{ now()->format('d M Y') }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Index No</th>
                <th>Present</th>
                <th>Absent</th>
                <th>Late</th>
                <th>Total</th>
                <th>Percentage</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData as $index => $data)
            <tr class="{{ $data['flagged'] ? 'flagged' : '' }}">
                <td>{{ $index + 1 }}</td>
                <td><strong>{{ $data['student']->full_name }}</strong></td>
                <td>{{ $data['student']->index_no }}</td>
                <td>{{ $data['present'] }}</td>
                <td>{{ $data['absent'] }}</td>
                <td>{{ $data['late'] }}</td>
                <td>{{ $data['total'] }}</td>
                <td><strong>{{ $data['percentage'] }}%</strong></td>
                <td>
                    @if($data['flagged'])
                        <span class="badge badge-low">Below 80%</span>
                    @else
                        <span class="badge badge-ok">Good</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        This report was automatically generated by SAMS — Student Attendance Management System · SLIATE Dambawela
    </div>
</body>
</html>